site:
    title: Payara Documentation Preview
    start_page: docs::Overview.adoc
content:
    sources:
    - url: ./
      start_path: docs
      branches: master
    - url: ./
      start_path: enterprise/docs
      branches: [v5.36.0]
    - url: ./
      start_path: community/docs
      branches: [v5.2021.10]
asciidoc:
    attributes:
        attribute-missing: 'skip'
ui:
    bundle:
        url: https://github.com/payara/antora-ui-default/raw/master/build/ui-bundle.zip
        snapshot: true
runtime:
    fetch: true
output:
    dir: ./build/html
