site:
  title: Payara Enterprise Documentation
  start_page: docs::Overview.adoc
content:
  sources:
    - url: .
      start_path: docs
      branches: master
    - url: https://github.com/AlanRoth/Payara-Documentation.git
      start_path: enterprise/docs
      branches: [e*]
asciidoc:
  attributes:
    attribute-missing: 'skip'
ui:
  bundle:
    url: https://github.com/payara/antora-ui-default/raw/master/build/ui-bundle.zip
    snapshot: true
runtime:
  fetch: true
output:
    dir: ./../html-new/enterprise
